export default{
    SET_CURRENT_USER_PROFILE: 'SET_CURRENT_USER_PROFILE',
    SET_CURRENT_USER_FOLLOWERS: 'SET_CURRENT_USER_FOLLOWERS',
    SET_CURRENT_USER_REPOSITORIES: 'SET_CURRENT_USER_REPOSITORIES',
    SET_CURRENT_USER_INFO: 'SET_CURRENT_USER_INFO',
}