export default{
    INITIALIZE_START:'INITIALIZE_START',
    INITIALIZE_FINISH:'INITIALIZE_FINISH',
    CHANGE_PRINCIPAL_COLOR: 'CHANGE_PRINCIPAL_COLOR',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    INITIALIZE_CONFIGURATION: 'INITIALIZE_CONFIGURATION',
    SET_CURRENT_GAME: 'SET_CURRENT_GAME',
}