export default{
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    SET_ADS_CODE: 'SET_ADS_CODE',
    ADS_CODE_VALIDATION_START: 'ADS_CODE_VALIDATION_START',
    ADS_CODE_VALIDATION_FINISH: 'ADS_CODE_VALIDATION_FINISH',
}